import React from 'react';

const thingsILike = [
    "You make me feel like the luckiest person alive.",
    "You are my greatest love story.",
    "You make loving you the easiest thing in the world.",
    "You make me feel like I’ve found my soulmate.",
    "I would find you and love you in every lifetime!!!!",
    "You accept me for who I am.",
    "You always make me feel loved, no matter what.",
    "The way we plan our future together.",
    "You believe in me",
    "You never let me feel alone.",
    "You bring out the best version of me.",
    "You never make me doubt how much you care.",
    "You show your love through actions, not just words.",
    "How you text me just to say you’re thinking about me.",
    "You always know exactly what I need before I say it.",
    "You call me your husband",
    "I love to sleep with you",
    "Watch movies with you",
    "To hike with you",
    "Your eyes",
    "Your smile",
    "Your hair",
    "Your lips",
    "The good relationship with your family",
    "The good relationship with my family",
    "To have your back every time you need",
    "You appreciate the thing i doing for you",
    "You remember small things that matter to me.",
    "You always check if I got home safely.",
    "You always make sure I eat enough.",
    "You make me feel better while im sad",
    "You trust me fully",
    "You are open with me",
    "Im your safest place",
    "You are my safest place",
    "You laugh at my jokes",
    "You make me feel understood.",
    "You make me feel important.",
    "You make me feel like I’m your favorite person in the world.",
    "You make me feel loved even when we’re apart.",
    "You make me feel like I can do anything with you by my side.",
    "You make me feel special every single day.",
    "You make me feel proud to be yours.",
    "You make me feel like I’m home when I’m with you.",
    "The way you smile when you’re embarrassed.",
    "The way you blush when I compliment you.",
    "The little happy dance you do when you’re excited.",
    "The way you light up when you see me.",
    "Your adorable facial expressions.",
    "The way you look at me when you think I’m not watching.",
    "The way you stick out your tongue when you concentrate.",
    "How you get all excited about small things.",
    "The cute nicknames you give me.",
    "The way you get competitive over silly games.",
    "I know I can always count on you.",
    "You are stubborn about things that are important to you.",
    "You always have my back, no matter what.",
    "I never have to question your loyalty.",
    "You trust me completely.",
    "You believe in our relationship.",
    "I never have to pretend around you.",
    "You make me feel secure in us.",
    "You defend me when I’m not around.",
    "I know you’ll always be honest with me.",
    "You always put your loved ones first.",
    "You’re kind to strangers.",
    "You’re always willing to help someone in need.",
    "You have such a big heart.",
    "You never judge people unfairly.",
    "You always try to see things from others’ perspectives.",
    "You always remember important things about people.",
    "You check in on your friends when they’re feeling down.",
    "You always spread positivity.",
    "You inspire me to be more caring.",
    "We balance each other out perfectly.",
    "You complete my sentences.",
    "We can be silly and serious together.",
    "You make even silence feel comfortable.",
    "You’re my favorite person to do nothing with.",
    "We understand each other without words.",
    "You’re my best friend and my love.",
    "We laugh at the same weird things.",
    "You make everything feel better when you’re around.",
    "I can’t imagine my life without you.",
    "You always surprise me in the best ways.",
    "You have the most beautiful way of seeing the world.",
    "Your handwriting is so cute.",
    "The way you wrinkle your nose when you’re thinking.",
    "You have the softest hands.",
    "You always smell amazing.",
    "Your sleepy voice is adorable.",
    "You look beautiful even when you wake up.",
    "The way you brighten up every room you walk into.",
    "Our favorite songs that remind me of you.",
    "The way we make memories out of the simplest moments.",
    "Our matching inside jokes.",
    "The places we still want to visit together.",
    "The stories we tell each other.",
    "The way we share our dreams and goals.",
    "You make me want to be a better person.",
    "You inspire me to be more patient.",
    "You encourage me to go after my dreams.",
    "You make me appreciate the little things in life.",
    "You show me the beauty in kindness.",
    "You make me believe in love even more.",
    "You inspire me to be more confident.",
    "You remind me that love is about the small things.",
    "You teach me to appreciate every moment.",
    "You make me want to spend forever with you.",
    "I can’t put into words how much you mean to me.",
    "You make me feel things I’ve never felt before.",
    "Loving you comes so naturally.",
    "Every day with you feels like a blessing.",
    "You make life feel like a fairytale.",
    "I love you more than I can ever express.",
    "I don’t need a reason to love you—I just do.",
    "You’re my person.",
    "I’d choose you in every lifetime.",
    "Your passion for life inspires me.",
    "The way you challenge me to grow.",
    "The way your eyes sparkle when you talk about something you love.",
    "You make me laugh until my stomach hurts.",
    "The way you make every moment feel magical.",
    "You give the best hugs in the world.",
    "You give the best kisses in the world",
    "You are my biggest adventure."
  ];
  
  
//"You are my greatest love story."
const ThingsILike = () => {
  return (
    <div className="things-i-like">
      <h1>100 Things I Like About You, Simona</h1>
      <ul>
        {thingsILike.map((thing, index) => (
          <li key={index}>{index + 1}. {thing}</li>
        ))}
      </ul>
    </div>
  );
};

export default ThingsILike;
